# 피마 인디언 당뇨병 사례

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
# 실행할 때마다 같은 결과를 출력하기 위한 seed 값 설정
seed =2021
np.random.seed(seed)
tf.random.set_seed(seed)

### 데이터 전처리

In [3]:
from google.colab import files
uploaded = files.upload()
filename = list(uploaded.keys())[0]
Data_set = np.loadtxt(filename, delimiter=",")
Data_set[:3, :]

Saving pima-indians-diabetes.csv to pima-indians-diabetes (1).csv


array([[  6.   , 148.   ,  72.   ,  35.   ,   0.   ,  33.6  ,   0.627,
         50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   ,  29.   ,   0.   ,  26.6  ,   0.351,
         31.   ,   0.   ],
       [  8.   , 183.   ,  64.   ,   0.   ,   0.   ,  23.3  ,   0.672,
         32.   ,   1.   ]])

In [4]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_norm = scaler.fit_transform(Data_set[:, :-1])

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X_norm, Data_set[:, -1], stratify=Data_set[:, -1], random_state=seed
)
X_train.shape, X_test.shape

((576, 8), (192, 8))

### 모델 정의/설정/학습/평가

In [6]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [7]:
# 딥러닝 모델 설정
model = Sequential([
    Dense(12, input_shape=(8,), activation='relu'),
    Dense(8, activation='relu'),
    Dense(1, activation='sigmoid')
])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 12)                108       
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 104       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 9         
Total params: 221
Trainable params: 221
Non-trainable params: 0
_________________________________________________________________


In [8]:
# 모델 컴파일 
model.compile(loss='binary_crossentropy', 
              optimizer='adam',
              metrics=['accuracy'])

In [9]:
# 모델 실행
history = model.fit(X_train, y_train, validation_split=0.2, epochs=200, batch_size=50)

Epoch 1/200
10/10 [==============================] - 1s 50ms/step - loss: 0.6544 - accuracy: 0.6107 - val_loss: 0.6141 - val_accuracy: 0.6379
Epoch 2/200
10/10 [==============================] - 0s 6ms/step - loss: 0.6274 - accuracy: 0.6698 - val_loss: 0.5967 - val_accuracy: 0.6466
Epoch 3/200
10/10 [==============================] - 0s 5ms/step - loss: 0.6065 - accuracy: 0.6923 - val_loss: 0.5823 - val_accuracy: 0.6552
Epoch 4/200
10/10 [==============================] - 0s 5ms/step - loss: 0.5886 - accuracy: 0.7010 - val_loss: 0.5718 - val_accuracy: 0.6638
Epoch 5/200
10/10 [==============================] - 0s 5ms/step - loss: 0.5858 - accuracy: 0.6975 - val_loss: 0.5635 - val_accuracy: 0.6466
Epoch 6/200
10/10 [==============================] - 0s 5ms/step - loss: 0.5648 - accuracy: 0.7288 - val_loss: 0.5562 - val_accuracy: 0.6466
Epoch 7/200
10/10 [==============================] - 0s 6ms/step - loss: 0.5505 - accuracy: 0.7117 - val_loss: 0.5510 - val_accuracy: 0.6552
Epoch 8/200


In [10]:
acc = model.evaluate(X_test, y_test)
print(f'Accuracy: {acc[1]:.4f}')

6/6 [==============================] - 0s 2ms/step - loss: 0.4788 - accuracy: 0.8073
Accuracy: 0.8073


### 테스트

In [11]:
index = 10
test_data = X_test[index, :].reshape(1,-1)
test_data

array([[-0.54791859,  2.38188392,  0.04624525,  4.92186584, -0.69289057,
         0.34362394,  0.31144581,  2.44704844]])

In [12]:
label = y_test[index]
int(label)

1

In [13]:
pred = model.predict(test_data)
pred

array([[0.72384053]], dtype=float32)

In [14]:
int(pred[0][0] > 0.5)

1

### 은닉층 추가

In [15]:
model2 = Sequential([
    Dense(24, input_shape=(8,), activation='relu'),
    Dense(12, activation='relu'),
    Dense(8, activation='relu'),
    Dense(1, activation='sigmoid')
])
model2.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 24)                216       
_________________________________________________________________
dense_4 (Dense)              (None, 12)                300       
_________________________________________________________________
dense_5 (Dense)              (None, 8)                 104       
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 9         
Total params: 629
Trainable params: 629
Non-trainable params: 0
_________________________________________________________________


In [16]:
model2.compile(loss='binary_crossentropy', 
               optimizer='adam',
               metrics=['accuracy'])

In [17]:
model2.fit(X_train, y_train, validation_split=0.2, epochs=100, batch_size=50)

Epoch 1/100
10/10 [==============================] - 1s 21ms/step - loss: 0.6395 - accuracy: 0.7005 - val_loss: 0.6443 - val_accuracy: 0.6034
Epoch 2/100
10/10 [==============================] - 0s 5ms/step - loss: 0.6100 - accuracy: 0.7309 - val_loss: 0.6337 - val_accuracy: 0.6379
Epoch 3/100
10/10 [==============================] - 0s 5ms/step - loss: 0.6024 - accuracy: 0.7237 - val_loss: 0.6249 - val_accuracy: 0.6207
Epoch 4/100
10/10 [==============================] - 0s 19ms/step - loss: 0.5794 - accuracy: 0.7334 - val_loss: 0.6182 - val_accuracy: 0.6121
Epoch 5/100
10/10 [==============================] - 0s 5ms/step - loss: 0.5723 - accuracy: 0.7279 - val_loss: 0.6117 - val_accuracy: 0.6207
Epoch 6/100
10/10 [==============================] - 0s 5ms/step - loss: 0.5631 - accuracy: 0.7492 - val_loss: 0.6039 - val_accuracy: 0.6207
Epoch 7/100
10/10 [==============================] - 0s 6ms/step - loss: 0.5353 - accuracy: 0.7437 - val_loss: 0.5962 - val_accuracy: 0.6293
Epoch 8/100

In [18]:
acc = model2.evaluate(X_test, y_test)
print(f'Accuracy: {acc[1]:.4f}')

6/6 [==============================] - 0s 2ms/step - loss: 0.5248 - accuracy: 0.7604
Accuracy: 0.7604
